version: '3.6'

services:
  webhook-apps:
    container_name: webhook-apps
    image: ghcr.io/kth-biblioteket/webhook-apps:main
    restart: always
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.webhook-apps.rule=Host(`${HOST}`) && PathPrefix(`${PATHPREFIX}`)"
      - "traefik.http.routers.webhook-apps.middlewares=webhook-apps-stripprefix"
      - "traefik.http.middlewares.webhook-apps-stripprefix.stripprefix.prefixes=${PATHPREFIX}"
      - "traefik.http.routers.webhook-apps.entrypoints=websecure"
      - "traefik.http.routers.webhook-apps.tls=true"
      - "traefik.http.routers.webhook-apps.tls.certresolver=myresolver"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /local/docker:/docker:ro
    networks:
      - "apps-net"

networks:
  apps-net:
    external: true
